#!/bin/sh

curl https://api.riskrecon.com/v0/cpe/openapi | jq . >openapi/v0-cpe.json
curl https://api.riskrecon.com/v1/openapi | jq . >openapi/v1.json
curl https://api.riskrecon.com/v2/openapi | jq . >openapi/v2.json
